on: [push]

jobs:
           
   robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: listar diretorio 
        run: ls    
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
